name: Java CI

on: [push]

jobs:
  build_and_test:
    strategy:
      matrix:
        jdkversion: [8, 11, 17, 21]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdkversion }}
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew clean shadowJar
